security:
    password_hashers:
        # Configurez un hasher "plaintext" pour les tests
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 
            algorithm: plaintext  # <-- Important !
            ignore_case: false
        
        # Ou spÃ©cifiquement pour Gestionnaire
        App\Entity\Gestionnaire:
            algorithm: plaintext
            ignore_case: false

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Gestionnaire
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_dashboard
                username_parameter: login
                password_parameter: password
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }  
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_GESTIONNAIRE }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10