app_home_redirect:
    path: /
    methods: GET
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_login.1
        permanent: true